---
title: "Rworksheet_Rabago#4b"
author: "James Bryan Rabago"
date: "2024-10-29"
output: pdf_document
---
1.
```{r}

vectorA <- c(1, 2, 3, 4, 5)
matrix_result <- matrix(0, nrow = 5, ncol = 5)


for (i in 1:5) {
  matrix_result[i, i] <- abs(vectorA[i])  
}


print(matrix_result)

```

2.
```{r}
vectorB <- c(1,2,3,4,5)

for (i in vectorB){
  cat(rep("*",i), "\n")
}
```
3
```{r}
fibonacci_sequence <- function(start) {
  a <- 0
  b <- 1
  fib_sequence <- c()

  repeat {
    fib <- a + b
    a <- b
    b <- fib
    
    
    if (fib > 500) {
      break
    }

    
    if (fib >= start) {
      fib_sequence <- c(fib_sequence, fib)
    }
  }

  return(fib_sequence)
}


start_input <- 8  
if (start_input <= 0) {
  cat("Please enter a number greater than 0.\n")
} else {
 
  result <- fibonacci_sequence(start_input)
  cat("Fibonacci sequence starting from", start_input, "up to 500:\n")
  print(result)
}


```
4.a.
```{r}
datas <- read.csv("/cloud/project/Worksheet4/Household Data.csv")
```

4.b.
```{r}
male <- subset(datas, Gender == "M")
male
female <- subset(datas, Gender == "F")
female
numbermale <- nrow(male)
numberfemale <- nrow(female)
cat("Number of observations for Male:", numbermale, "\n")
cat("Number of observations for Female:", numberfemale, "\n")
```

4.c.
```{r}
Plotting <- c(numbermale,numberfemale)
names(Plotting) <- c("Male", "Female")
barplot(Plotting, main = "Male and Female", xlab = "Gender", ylab = "Total Numbers", col = c("red", "green"),legend.text = TRUE, beside = TRUE)
```
5
```{r}
bills <- c("Food", "Electricity", "Savings", "Miscellaneous")
values <- c(60, 10, 5, 25)

Bills <- matrix(values, nrow = 1, ncol = length(bills), dimnames = list(NULL, bills))
Bills

Plotters <- pie(values, labels = c("Food", "Electricity", "Savings", "Miscellaneous"),col = c("red", "orange", "yellow", "green"), main = "Expenditures" )
```

6.a.
```{r}
data(iris)

str(iris)

```
6.b.
```{r}
meanvalues <- colMeans(iris[, 1:4])
meanvalues

```
6.c.
```{r}
species_count <- table(iris$Species)

pie(species_count,
    main = "Species Distribution",
    col = c("blue", "violet", "pink"),
    labels = paste(names(species_count),species_count))

```
6.d.
```{r}
setosa <- subset(iris, Species == "setosa")
versicolor <- subset(iris, Species == "versicolor")
virginica <- subset(iris, Species == "virginica")

last6_setosa <- tail(setosa)
last6_versicolor <- tail(versicolor)
last6_virginica <- tail(virginica)

cat("Last six rows of Setosa:\n")
print(last6_setosa)

cat("\nLast six rows of Versicolor:\n")
print(last6_versicolor)

cat("\nLast six rows of Virginica:\n")
print(last6_virginica)

```
6.e.
```{r}
plot(iris$Sepal.Length, iris$Sepal.Width,
     col = iris$Species,
     pch = 19,
     main = "Iris Dataset",
     sub = "Sepal Width and Length",
     xlab = "Sepal Length",
     ylab = "Sepal Width")


legend("topright", legend = levels(iris$Species), col = 1:3, pch = 19)

```

6.f.


-The scatterplot shows the relationship between sepal width and length for different iris flower species. Versicolor and Virginica overlap a lot and have similar sepal sizes. However, Setosa is easy to identify because it has smaller sepal sizes than the other two species.



7.a.
```{r}
library(readxl)  
alexa_data <- read_excel("alexa_file.xlsx")


alexa_data$variation <- gsub("Black\\s+Dot", "Black Dot", alexa_data$variation)
alexa_data$variation <- gsub("Black\\s+Plus", "Black Plus", alexa_data$variation)
alexa_data$variation <- gsub("Black\\s+Show", "Black Show", alexa_data$variation)
alexa_data$variation <- gsub("Black\\s+Spot", "Black Spot", alexa_data$variation)
alexa_data$variation <- gsub("White\\s+Dot", "White Dot", alexa_data$variation)
alexa_data$variation <- gsub("White\\s+Plus", "White Plus", alexa_data$variation)
alexa_data$variation <- gsub("White\\s+Show", "White Show", alexa_data$variation)
alexa_data$variation <- gsub("White\\s+Spot", "White Spot", alexa_data$variation)


table(alexa_data$variation)
```

7.b.
```{r}
library(dplyr)


variations_count <- alexa_data %>%
  count(variation, name = "Total")


save(variations_count, file = "variations.RData")


print(variations_count)
```
7.c.
```{r}
library(ggplot2)

load("variations.RData")


ggplot(variations_count, aes(x = variation, y = Total, fill = variation)) +
  geom_bar(stat = "identity") +
  ggtitle("Total Count of Alexa Variations") +
  xlab("Variation") +
  ylab("Total Numbers") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set3")
```
7.d.
```{r}
variations_count$Category <- ifelse(grepl("Black", variations_count$variation), "Black Variants", 
                                    ifelse(grepl("White", variations_count$variation), "White Variants", NA))

black_white_variants <- variations_count %>% filter(!is.na(Category))


ggplot(black_white_variants, aes(x = variation, y = Total, fill = variation)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Category, scales = "free_x") +  
  ggtitle("Counts of Alexa Black and White Variants") +
  xlab("Variation") +
  ylab("Total Numbers") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set2")  
```

